var products = [
    { id: 1, idf: 99, imgUrl: '../images/Low-profile-unisex-running-shoe.jpg', name: 'Running shoe', price: '60', category: 'shoe' },
    { id: 2, idf: 109,imgUrl: '../images/product-8.jpg', name: 'wall clock', price: '180', category: 'clock' },
    { id: 3, idf: 119, imgUrl: '../images/Polo-shirt-red.jpg', name: ' polo shirt red', price: '40', category: 'shirt' },
    { id: 4, idf: 129,imgUrl: '../images/Pure-women-running-shoes.jpg', name: 'womens shoes', price: '100', category: 'shoe' },
    { id: 5, idf: 139,imgUrl: '../images/product-3.jpg', name: 'Optical scanner', price: '200', category: 'scanner' },
    { id: 6, idf: 149, imgUrl: '../images/Polo-shirt-bink.jpg', name: ' polo shirt bink', price: '40', category: 'shirt' },
    { id: 7, idf: 159,imgUrl: '../images/product-2.jpg', name: 'Wooden clock', price: '100', category: 'clock' },
    { id: 8, idf: 169, imgUrl: '../images/Polo-shirt-black.jpg', name: ' polo shirt black', price: '40', category: 'shirt' },
    { id: 9, idf: 179, imgUrl: '../images/Mason watch with quartz movement and multiple.jpg', name: 'Mason watch', price: '100', category: 'clock' },
    { id: 10, idf: 189, imgUrl: '../images/Analog watch.jpg', name: 'Analog watch', price: 120, category: 'clock' },
    { id: 11, idf: 199, imgUrl: '../images/Enticer analog watch from Casio.jpg', name: 'Watch Casio', price: '150', category: 'clock' },
    { id: 12, idf: 209, imgUrl: '../images/Standart watch for men.jpg', name: 'Standart watch', price: '200', category: 'clock' },
    { id: 13, idf: 219,imgUrl: '../images/Mens-sports-shoes.jpg', name: 'Sports shoes', price: '150', category: 'shoe' },
    { id: 14, idf: 229,imgUrl: '../images/Ultra-sports-shoes-for-men.jpg', name: 'Ultra sports', price: '110', category: 'shoe' },
    { id: 15, idf: 239,imgUrl: '../images/Lycra jeans pants.jpg', name: 'Lycra jeans', price: '170', category: 'pants' },
    { id: 16, idf: 249,imgUrl: '../images/Mens workout pants.jpg', name: 'Mens workout', price: '100', category: 'pants' },
    { id: 17, idf: 259,imgUrl: '../images/Original jeans pants.jpg', name: 'Original jeans', price: '200', category: 'pants' },
    { id: 18, idf: 269,imgUrl: '../images/Skinny jeans pants.jpg', name: 'Skinny jeans', price: '180', category: 'pants' },
    { id: 19, idf: 279,imgUrl: '../images/Sports pants.jpg', name: 'Sports pants', price: '150', category: 'pants' },
    { id: 20, idf: 289,imgUrl: '../images/product-11.jpg', name: 'Aroma diffuser', price: '50', category: 'diffuser' },
  ]